### PR TITLE
Some small fixes while reviewing the text

### PR DESCRIPTION
**Pull request by gwtaylor**
Hello!
I was asked to teach a [new course in Systems](https://uoguelph-engg3130.github.io/engg3130/) at the University of Guelph. This book has been an incredible resource, and both myself and the class of 16 students is really enjoying it and the exercises.
The least I can do is suggest some edits, but I feel that owe you much more for making this open and accessible.
[Graham](http://www.uoguelph.ca/~gwtaylor)

### CODE REVIEW

**Comment by AllenDowney** [comment]
Thanks for your kind words.  I am delighted that the book was useful for you.  And thanks for these corrections!

It looks like your editor removes spaces from the ends of lines, which is generally a good thing, but it means that these commits have a lot of white space changes, which makes it hard for me to find the actual typos.

Would it be possible to send me just a list of typos, or a PR without the white space changes?

I am sorry to look a gift horse in the mouth, but if it is not too much trouble, I would be grateful!

**Comment by AllenDowney** [comment]
Actually, it looks like just one commit had this problem, and I was able to review it.

Merging!

**Comment by AllenDowney** [comment]
Thanks again!

**Comment by gwtaylor** [comment]
My pleasure. I have a few more edits & suggestions built up over the last part of the term. Scrambling now with marking and the like but please expect some more feedback coming during the summer.

**Pull request merged**
